import type { TelegramUpdate } from './types/telegram'
import { TelegramAPI } from './telegram'
import {
  handleStartCommand,
  handleDoneCommand,
  handleCancelCommand,
  handleHelpCommand,
  handleForwardedMessage
} from './handlers/commands'
import { handleInlineQuery } from './handlers/inline'
import { handleCallbackQuery } from './handlers/callback'
import { parseShareId } from './crypto'
import { getAssetFromKV } from '@cloudflare/kv-asset-handler'
// @ts-ignore - This is generated by wrangler
import manifestJSON from '__STATIC_CONTENT_MANIFEST'

const assetManifest = JSON.parse(manifestJSON)

// Encrypted bundle storage format
interface EncryptedBundle {
  encrypted: string
  meta: {
    messageCount: number
    createdAt: number
    creatorId: number
  }
}

export interface Env {
  BUNDLES: KVNamespace
  __STATIC_CONTENT: KVNamespace // Auto-injected by wrangler for Workers Sites
  BOT_TOKEN: string
  BOT_USERNAME: string
  WEBHOOK_SECRET?: string
}

export default {
  async fetch(request: Request, env: Env, ctx: ExecutionContext): Promise<Response> {
    const url = new URL(request.url)
    const baseUrl = `${url.protocol}//${url.host}`

    // Handle webhook setup
    if (url.pathname === '/setup-webhook') {
      const api = new TelegramAPI(env.BOT_TOKEN)
      const webhookUrl = `${baseUrl}/webhook`
      await api.setWebhook(webhookUrl)
      return new Response(`Webhook set to: ${webhookUrl}`)
    }

    // Handle webhook info
    if (url.pathname === '/webhook-info') {
      const api = new TelegramAPI(env.BOT_TOKEN)
      const info = await api.getWebhookInfo()
      return new Response(JSON.stringify(info, null, 2), {
        headers: { 'Content-Type': 'application/json' },
      })
    }

    // Handle Telegram webhook
    if (url.pathname === '/webhook' && request.method === 'POST') {
      try {
        const update: TelegramUpdate = await request.json()
        await handleUpdate(update, env, baseUrl)
        return new Response('OK')
      } catch (error) {
        console.error('Webhook error:', error)
        return new Response('Error', { status: 500 })
      }
    }

    // Serve static frontend from /view path
    if (url.pathname.startsWith('/view')) {
      try {
        // Strip /view prefix for KV lookup (assets are stored without prefix)
        const assetUrl = new URL(request.url)
        let assetPath = assetUrl.pathname.replace(/^\/view/, '') || '/'

        // If accessing root, serve index.html
        if (assetPath === '' || assetPath === '/') {
          assetPath = '/index.html'
        }
        assetUrl.pathname = assetPath

        return await getAssetFromKV(
          {
            request: new Request(assetUrl.toString(), request),
            waitUntil: ctx.waitUntil.bind(ctx),
          },
          {
            ASSET_NAMESPACE: env.__STATIC_CONTENT,
            ASSET_MANIFEST: assetManifest,
          }
        )
      } catch (e) {
        // If asset not found, return index.html for SPA routing
        const assetUrl = new URL(request.url)
        assetUrl.pathname = '/index.html'
        try {
          return await getAssetFromKV(
            {
              request: new Request(assetUrl.toString(), request),
              waitUntil: ctx.waitUntil.bind(ctx),
            },
            {
              ASSET_NAMESPACE: env.__STATIC_CONTENT,
              ASSET_MANIFEST: assetManifest,
            }
          )
        } catch {
          return new Response('Not found', { status: 404 })
        }
      }
    }

    // API: Get bundle data (returns encrypted data)
    if (url.pathname.startsWith('/api/bundle/')) {
      const bundleId = url.pathname.split('/').pop()
      if (!bundleId) {
        return new Response('Bundle ID required', { status: 400 })
      }

      const storedData = await env.BUNDLES.get<EncryptedBundle>(`bundle:${bundleId}`, 'json')
      if (!storedData) {
        return new Response('Bundle not found', { status: 404 })
      }

      // Return encrypted data - decryption happens client-side
      return new Response(JSON.stringify(storedData), {
        headers: {
          'Content-Type': 'application/json',
          'Access-Control-Allow-Origin': '*',
        },
      })
    }

    // API: Get file proxy (for Telegram files)
    if (url.pathname.startsWith('/api/file/')) {
      const fileId = url.pathname.split('/').pop()
      if (!fileId) {
        return new Response('File ID required', { status: 400 })
      }

      const api = new TelegramAPI(env.BOT_TOKEN)
      try {
        const file = await api.getFile(fileId)
        if (!file.file_path) {
          return new Response('File not available', { status: 404 })
        }

        const fileUrl = api.getFileUrl(file.file_path)
        const fileResponse = await fetch(fileUrl)

        return new Response(fileResponse.body, {
          headers: {
            'Content-Type': fileResponse.headers.get('Content-Type') || 'application/octet-stream',
            'Cache-Control': 'public, max-age=86400',
            'Access-Control-Allow-Origin': '*',
          },
        })
      } catch (error) {
        console.error('File fetch error:', error)
        return new Response('Failed to fetch file', { status: 500 })
      }
    }

    // Serve the Mini App viewer (will be handled by Cloudflare Pages or static assets)
    if (url.pathname === '/view' || url.pathname.startsWith('/view/')) {
      return serveViewerPage(env.BOT_USERNAME)
    }

    // Health check
    if (url.pathname === '/health') {
      return new Response('OK')
    }

    // Default: serve index/help page
    return new Response(getIndexHtml(env.BOT_USERNAME), {
      headers: { 'Content-Type': 'text/html' },
    })
  },
}

async function handleUpdate(update: TelegramUpdate, env: Env, baseUrl: string): Promise<void> {
  const api = new TelegramAPI(env.BOT_TOKEN)

  // Handle inline query
  if (update.inline_query) {
    await handleInlineQuery(api, update.inline_query, env.BUNDLES, env.BOT_USERNAME)
    return
  }

  // Handle callback query
  if (update.callback_query) {
    await handleCallbackQuery(api, update.callback_query, env.BUNDLES)
    return
  }

  // Handle message
  const msg = update.message
  if (!msg) return

  // Only handle private chats
  if (msg.chat.type !== 'private') return

  const text = msg.text || ''

  // Handle commands
  if (text.startsWith('/start')) {
    await handleStartCommand(api, msg, env.BUNDLES, env.BOT_USERNAME)
    return
  }

  if (text === '/done') {
    await handleDoneCommand(api, msg, env.BUNDLES, env.BOT_USERNAME, baseUrl)
    return
  }

  if (text === '/cancel') {
    await handleCancelCommand(api, msg, env.BUNDLES)
    return
  }

  if (text === '/help') {
    await handleHelpCommand(api, msg, env.BOT_USERNAME)
    return
  }

  // Handle forwarded messages
  if (msg.forward_from || msg.forward_from_chat || msg.forward_sender_name || msg.forward_date) {
    await handleForwardedMessage(api, msg, env.BUNDLES)
    return
  }

  // Handle regular messages during session (treat as content to bundle)
  if (msg.text || msg.photo || msg.document || msg.video || msg.audio || msg.voice || msg.sticker || msg.animation) {
    // Check if user has an active session
    const sessionData = await env.BUNDLES.get(`session:${msg.from!.id}`)
    if (sessionData) {
      await handleForwardedMessage(api, msg, env.BUNDLES)
    }
  }
}

function serveViewerPage(botUsername: string): Response {
  const html = `<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no">
  <title>Messages Bundle</title>
  <script src="https://telegram.org/js/telegram-web-app.js"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/pako/2.1.0/pako.min.js"></script>
  <style>
    :root {
      --bg-color: var(--tg-theme-bg-color, #ffffff);
      --text-color: var(--tg-theme-text-color, #000000);
      --hint-color: var(--tg-theme-hint-color, #999999);
      --link-color: var(--tg-theme-link-color, #3390ec);
      --bubble-bg: var(--tg-theme-secondary-bg-color, #f0f0f0);
      --section-bg: var(--tg-theme-section-bg-color, #ffffff);
    }
    
    * { margin: 0; padding: 0; box-sizing: border-box; }
    
    body {
      font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, 'Helvetica Neue', Arial, sans-serif;
      background: var(--bg-color);
      color: var(--text-color);
      min-height: 100vh;
      line-height: 1.4;
      -webkit-font-smoothing: antialiased;
    }
    
    .container {
      max-width: 600px;
      margin: 0 auto;
      padding-bottom: 20px;
    }
    
    /* Date Header - Sticky */
    .date-header {
      position: sticky;
      top: 0;
      z-index: 10;
      text-align: center;
      padding: 12px 0 8px;
    }
    
    .date-header span {
      display: inline-block;
      padding: 4px 12px;
      background: color-mix(in srgb, var(--text-color) 60%, transparent);
      backdrop-filter: blur(12px);
      -webkit-backdrop-filter: blur(12px);
      border-radius: 14px;
      color: var(--section-bg);
      font-size: 13px;
      font-weight: 500;
    }
    
    /* Sender Group */
    .sender-group {
      display: flex;
      margin: 12px 8px;
    }
    
    .avatar-container {
      display: flex;
      width: 46px;
      min-width: 46px;
      max-width: 46px;
      justify-content: center;
      align-items: flex-end;
    }
    
    .avatar {
      position: sticky;
      bottom: 12px;
      z-index: 5;
      width: 38px;
      height: 38px;
      border-radius: 50%;
      background: linear-gradient(135deg, var(--link-color), #7c4dff);
      display: flex;
      align-items: center;
      justify-content: center;
      color: white;
      font-size: 16px;
      font-weight: 600;
      text-transform: uppercase;
      flex-shrink: 0;
    }
    
    .messages-container {
      flex: 1;
      min-width: 0;
    }
    
    /* Sender Name - Sticky */
    .sender-name {
      position: sticky;
      top: 44px;
      z-index: 8;
      width: max-content;
      max-width: calc(100% - 20px);
      padding: 4px 10px;
      margin: 4px;
      background: color-mix(in srgb, var(--bg-color) 85%, transparent);
      backdrop-filter: blur(12px);
      -webkit-backdrop-filter: blur(12px);
      border-radius: 12px;
      font-size: 13px;
      font-weight: 600;
      color: var(--link-color);
    }
    
    /* Message Bubble */
    .bubble {
      border-radius: 4px 16px 16px 4px;
      width: max-content;
      min-width: 80px;
      max-width: calc(100vw - 80px);
      margin: 3px 4px;
      padding: 8px 12px;
      background: var(--bubble-bg);
      word-wrap: break-word;
      overflow-wrap: break-word;
    }
    
    .bubble:first-of-type {
      border-radius: 16px 16px 16px 4px;
    }
    
    .bubble:last-of-type {
      border-radius: 4px 16px 16px 16px;
    }
    
    .bubble:first-of-type:last-of-type {
      border-radius: 16px;
    }
    
    .bubble-text {
      font-size: 15px;
      white-space: pre-wrap;
    }
    
    .bubble-media {
      margin: 4px -4px;
    }
    
    .bubble-media img, .bubble-media video {
      max-width: 100%;
      max-height: 300px;
      border-radius: 10px;
      display: block;
    }
    
    .bubble-sticker img {
      max-width: 180px;
      max-height: 180px;
    }
    
    .bubble-file {
      display: flex;
      align-items: center;
      gap: 10px;
      padding: 8px 12px;
      background: color-mix(in srgb, var(--link-color) 15%, transparent);
      border-radius: 10px;
      margin: 4px 0;
    }
    
    .bubble-file-icon {
      font-size: 24px;
    }
    
    .bubble-file-info {
      flex: 1;
      min-width: 0;
    }
    
    .bubble-file-name {
      font-size: 14px;
      font-weight: 500;
      white-space: nowrap;
      overflow: hidden;
      text-overflow: ellipsis;
    }
    
    .bubble-file-type {
      font-size: 12px;
      color: var(--hint-color);
    }
    
    .bubble-time {
      font-size: 11px;
      color: var(--hint-color);
      text-align: right;
      margin-top: 4px;
    }
    
    /* Loading & Error */
    .loading, .error {
      display: flex;
      flex-direction: column;
      align-items: center;
      justify-content: center;
      min-height: 60vh;
      gap: 12px;
    }
    
    .loading-spinner {
      width: 40px;
      height: 40px;
      border: 3px solid var(--bubble-bg);
      border-top-color: var(--link-color);
      border-radius: 50%;
      animation: spin 0.8s linear infinite;
    }
    
    @keyframes spin {
      to { transform: rotate(360deg); }
    }
    
    .error { color: #ff3b30; }
    .error-icon { font-size: 48px; }
  </style>
</head>
<body>
  <div class="container" id="app">
    <div class="loading">
      <div class="loading-spinner"></div>
      <div>Decrypting messages...</div>
    </div>
  </div>
  
  <script>
    const tg = window.Telegram.WebApp;
    tg.ready();
    tg.expand();
    
    const shareId = tg.initDataUnsafe?.start_param || new URLSearchParams(window.location.search).get('startapp');
    
    if (!shareId) {
      showError('No bundle ID provided');
    } else {
      loadBundle(shareId);
    }
    
    function showError(msg) {
      document.getElementById('app').innerHTML = 
        '<div class="error"><div class="error-icon">😕</div><div>' + msg + '</div></div>';
    }
    
    // Parse shareId: bundleId_keyBase64
    function parseShareId(shareId) {
      const idx = shareId.indexOf('_');
      if (idx === -1) return null;
      return {
        bundleId: shareId.substring(0, idx),
        keyBase64: shareId.substring(idx + 1)
      };
    }
    
    // Base64url decode
    function base64UrlToArrayBuffer(base64url) {
      let base64 = base64url.replace(/-/g, '+').replace(/_/g, '/');
      while (base64.length % 4) base64 += '=';
      const binary = atob(base64);
      const bytes = new Uint8Array(binary.length);
      for (let i = 0; i < binary.length; i++) bytes[i] = binary.charCodeAt(i);
      return bytes.buffer;
    }
    
    // Import decryption key
    async function importKey(keyBase64) {
      const raw = base64UrlToArrayBuffer(keyBase64);
      return await crypto.subtle.importKey('raw', raw, { name: 'AES-GCM', length: 256 }, false, ['decrypt']);
    }
    
    // Decrypt and decompress data
    async function decrypt(encryptedData, key) {
      const combined = new Uint8Array(base64UrlToArrayBuffer(encryptedData));
      const iv = combined.slice(0, 12);
      const ciphertext = combined.slice(12);
      const decrypted = await crypto.subtle.decrypt({ name: 'AES-GCM', iv }, key, ciphertext);
      // Decompress with pako
      return pako.inflate(new Uint8Array(decrypted), { to: 'string' });
    }
    
    async function loadBundle(shareId) {
      try {
        const parsed = parseShareId(shareId);
        if (!parsed) {
          showError('Invalid link format');
          return;
        }
        
        const { bundleId, keyBase64 } = parsed;
        
        // Fetch encrypted data
        const response = await fetch('/api/bundle/' + bundleId);
        if (!response.ok) throw new Error('Bundle not found or expired');
        const storedData = await response.json();
        
        // Decrypt client-side
        const key = await importKey(keyBase64);
        const decrypted = await decrypt(storedData.encrypted, key);
        const bundle = JSON.parse(decrypted);
        
        renderBundle(bundle);
      } catch (error) {
        console.error('Decryption error:', error);
        showError('Failed to decrypt. Invalid or corrupted link.');
      }
    }
    
    function formatDate(ts) {
      const d = new Date(ts * 1000);
      const now = new Date();
      const diff = now - d;
      
      if (diff < 86400000 && d.getDate() === now.getDate()) return 'Today';
      if (diff < 172800000 && d.getDate() === now.getDate() - 1) return 'Yesterday';
      
      return d.toLocaleDateString(navigator.language, { 
        year: d.getFullYear() !== now.getFullYear() ? 'numeric' : undefined,
        month: 'long', 
        day: 'numeric' 
      });
    }
    
    function formatTime(ts) {
      return new Date(ts * 1000).toLocaleTimeString(navigator.language, { 
        hour: '2-digit', 
        minute: '2-digit',
        hour12: false 
      });
    }
    
    function getSenderId(msg) {
      if (msg.forward_from) return 'u' + msg.forward_from.id;
      if (msg.forward_from_chat) return 'c' + msg.forward_from_chat.id;
      if (msg.forward_sender_name) return 'n' + msg.forward_sender_name;
      if (msg.from) return 'u' + msg.from.id;
      return 'unknown';
    }
    
    function getSenderName(msg) {
      if (msg.forward_from) return [msg.forward_from.first_name, msg.forward_from.last_name].filter(Boolean).join(' ');
      if (msg.forward_from_chat) return msg.forward_from_chat.title || 'Chat';
      if (msg.forward_sender_name) return msg.forward_sender_name;
      if (msg.from) return [msg.from.first_name, msg.from.last_name].filter(Boolean).join(' ');
      return 'Unknown';
    }
    
    function getInitials(name) {
      return name.split(' ').map(w => w[0]).slice(0, 2).join('').toUpperCase() || '?';
    }
    
    function escapeHtml(text) {
      const d = document.createElement('div');
      d.textContent = text || '';
      return d.innerHTML;
    }
    
    function renderBundle(bundle) {
      // Group by date, then by sender
      const dateGroups = {};
      
      for (const msg of bundle.messages) {
        const ts = msg.forward_date || msg.date;
        const dateKey = formatDate(ts);
        if (!dateGroups[dateKey]) dateGroups[dateKey] = [];
        dateGroups[dateKey].push(msg);
      }
      
      let html = '';
      
      for (const [date, messages] of Object.entries(dateGroups)) {
        html += '<div class="date-header"><span>' + date + '</span></div>';
        
        let currentSenderId = null;
        let senderMessages = [];
        
        for (const msg of messages) {
          const senderId = getSenderId(msg);
          if (senderId !== currentSenderId) {
            if (currentSenderId !== null) {
              html += renderSenderGroup(senderMessages);
            }
            currentSenderId = senderId;
            senderMessages = [msg];
          } else {
            senderMessages.push(msg);
          }
        }
        
        if (senderMessages.length > 0) {
          html += renderSenderGroup(senderMessages);
        }
      }
      
      document.getElementById('app').innerHTML = html;
    }
    
    function renderSenderGroup(messages) {
      const sender = getSenderName(messages[0]);
      const initials = getInitials(sender);
      
      let html = '<div class="sender-group">';
      html += '<div class="avatar-container"><div class="avatar">' + initials + '</div></div>';
      html += '<div class="messages-container">';
      html += '<div class="sender-name">' + escapeHtml(sender) + '</div>';
      
      for (const msg of messages) {
        html += renderBubble(msg);
      }
      
      html += '</div></div>';
      return html;
    }
    
    function renderBubble(msg) {
      const ts = msg.forward_date || msg.date;
      let html = '<div class="bubble">';
      
      // Photo
      if (msg.photo && msg.photo.length > 0) {
        html += '<div class="bubble-media"><img src="/api/file/' + msg.photo[0].file_id + '" loading="lazy"></div>';
      }
      
      // Sticker
      if (msg.sticker) {
        if (msg.sticker.is_video || msg.sticker.is_animated) {
          html += '<div class="bubble-file"><span class="bubble-file-icon">🎨</span><div class="bubble-file-info"><div class="bubble-file-name">Sticker ' + (msg.sticker.emoji || '') + '</div><div class="bubble-file-type">Animated</div></div></div>';
        } else {
          html += '<div class="bubble-media bubble-sticker"><img src="/api/file/' + msg.sticker.file_id + '" loading="lazy"></div>';
        }
      }
      
      // Video
      if (msg.video) {
        html += '<div class="bubble-file"><span class="bubble-file-icon">🎬</span><div class="bubble-file-info"><div class="bubble-file-name">' + escapeHtml(msg.video.file_name || 'Video') + '</div><div class="bubble-file-type">' + formatDuration(msg.video.duration) + '</div></div></div>';
      }
      
      // Animation/GIF
      if (msg.animation) {
        html += '<div class="bubble-media"><video src="/api/file/' + msg.animation.file_id + '" autoplay loop muted playsinline></video></div>';
      }
      
      // Audio
      if (msg.audio) {
        html += '<div class="bubble-file"><span class="bubble-file-icon">🎵</span><div class="bubble-file-info"><div class="bubble-file-name">' + escapeHtml(msg.audio.title || msg.audio.performer || 'Audio') + '</div><div class="bubble-file-type">' + formatDuration(msg.audio.duration) + '</div></div></div>';
      }
      
      // Voice
      if (msg.voice) {
        html += '<div class="bubble-file"><span class="bubble-file-icon">🎤</span><div class="bubble-file-info"><div class="bubble-file-name">Voice message</div><div class="bubble-file-type">' + formatDuration(msg.voice.duration) + '</div></div></div>';
      }
      
      // Document
      if (msg.document) {
        const icon = getFileIcon(msg.document.mime_type);
        html += '<div class="bubble-file"><span class="bubble-file-icon">' + icon + '</span><div class="bubble-file-info"><div class="bubble-file-name">' + escapeHtml(msg.document.file_name || 'Document') + '</div><div class="bubble-file-type">' + (msg.document.mime_type || 'File') + '</div></div></div>';
      }
      
      // Text
      const text = msg.text || msg.caption || '';
      if (text) {
        html += '<div class="bubble-text">' + escapeHtml(text) + '</div>';
      }
      
      html += '<div class="bubble-time">' + formatTime(ts) + '</div>';
      html += '</div>';
      return html;
    }
    
    function formatDuration(sec) {
      if (!sec) return '';
      const m = Math.floor(sec / 60);
      const s = sec % 60;
      return m + ':' + (s < 10 ? '0' : '') + s;
    }
    
    function getFileIcon(mime) {
      if (!mime) return '📄';
      if (mime.startsWith('image/')) return '🖼';
      if (mime.startsWith('video/')) return '🎬';
      if (mime.startsWith('audio/')) return '🎵';
      if (mime.includes('pdf')) return '📕';
      if (mime.includes('zip') || mime.includes('rar') || mime.includes('7z')) return '📦';
      if (mime.includes('word') || mime.includes('document')) return '📝';
      if (mime.includes('sheet') || mime.includes('excel')) return '📊';
      return '📄';
    }
  </script>
</body>
</html>`

  return new Response(html, {
    headers: { 'Content-Type': 'text/html' },
  })
}

function getIndexHtml(botUsername: string): string {
  return `<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Messages Bundler Bot</title>
  <style>
    body {
      font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, sans-serif;
      max-width: 600px;
      margin: 40px auto;
      padding: 20px;
      line-height: 1.6;
    }
    h1 { color: #0088cc; }
    a { color: #0088cc; }
    .btn {
      display: inline-block;
      background: #0088cc;
      color: white;
      padding: 12px 24px;
      border-radius: 8px;
      text-decoration: none;
      margin-top: 20px;
    }
    .btn:hover { background: #006699; }
    code {
      background: #f0f0f0;
      padding: 2px 6px;
      border-radius: 4px;
    }
  </style>
</head>
<body>
  <h1>📦 Messages Bundler Bot</h1>
  <p>Bundle and share multiple forwarded Telegram messages in a single view.</p>
  
  <h2>How to use:</h2>
  <ol>
    <li>Send <code>/start</code> to the bot</li>
    <li>Forward messages you want to bundle</li>
    <li>Send <code>/done</code> to create the bundle</li>
    <li>Share using inline mode or the preview link</li>
  </ol>
  
  <a href="https://t.me/${botUsername}" class="btn">Open Bot</a>
</body>
</html>`
}
